name: Deploy to WP Engine

on:
  push:
    branches:
      - main    # or 'master', adjust to your repo's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.WPENGINE_SSH_KEY }}

      - name: Add WP Engine to known_hosts
        run: |
          ssh-keyscan git.wpengine.com >> ~/.ssh/known_hosts

      - name: Push to WP Engine
        run: |
          git remote add wpengine git@git.wpengine.com:phillypddev.git
          git push -f wpengine HEAD:master